{{- if and .Values.config.database.url (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ferrum.fullname" . }}
  labels:
    {{- include "ferrum.labels" . | nindent 4 }}
type: Opaque
stringData:
  FERRUM_DATABASE__URL: {{ .Values.config.database.url | quote }}
  {{- if .Values.config.storage.s3_access_key_id }}
  FERRUM_STORAGE__S3_ACCESS_KEY_ID: {{ .Values.config.storage.s3_access_key_id | quote }}
  FERRUM_STORAGE__S3_SECRET_ACCESS_KEY: {{ .Values.config.storage.s3_secret_access_key | quote }}
  {{- end }}
{{- end }}
