[package]
name = "ferrum-cli"
version = "0.3.0"
edition = "2021"
description = "CLI for Ferrum management"
license = "BUSL-1.1"

[[bin]]
name = "ferrum"
path = "src/main.rs"

[dependencies]
ferrum-drs = { path = "../../crates/ferrum-drs" }
ferrum-beacon = { path = "../../crates/ferrum-beacon" }
ferrum-ont = { path = "../../crates/ferrum-ont" }
ferrum-reference = { path = "../../crates/ferrum-reference" }
ferrum-core = { path = "../../crates/ferrum-core" }
ferrum-embed = { path = "../../crates/ferrum-embed" }
ferrum-mii-connect = { path = "../../crates/ferrum-mii-connect" }
ferrum-meta-connect = { path = "../../crates/ferrum-meta-connect" }
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "multipart"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
flate2 = "1"
tar = "0.4.46"
sha2 = "0.11"
hex = "0.4"
tempfile = "3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = "0.4"
ferrum-discovery = { path = "../../crates/ferrum-discovery" }
