// SPDX-License-Identifier: BUSL-1.1

//! Live GHGA/EGA export from a running Ferrum DRS (not the starter fixtures).

use ferrum_drs::types::DrsObject;
use std::path::PathBuf;

const GHGA_STARTER: &str =
    include_str!("../../../profiles/meta/fixtures/ghga-minimal-submission.yaml");
const EGA_STARTER: &str =
    include_str!("../../../profiles/meta/fixtures/ega-minimal-submission.yaml");

pub struct ExportOpts {
    pub profile: String,
    pub output: PathBuf,
    pub starter: bool,
    pub base_url: String,
    pub bearer: Option<String>,
}

pub fn starter_yaml(profile: &str) -> Result<&'static str, String> {
    match profile.to_ascii_lowercase().as_str() {
        "ghga" => Ok(GHGA_STARTER),
        "ega" => Ok(EGA_STARTER),
        other => Err(format!(
            "unknown export profile `{other}` (use ghga or ega). core/pathogen/h3africa: ferrum meta init"
        )),
    }
}

fn yaml_escape(s: &str) -> String {
    if s.chars().any(|c| c.is_whitespace() || ":#\"'".contains(c)) {
        format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
    } else {
        s.to_string()
    }
}

fn file_format(obj: &DrsObject) -> &'static str {
    let mime = obj.mime_type.as_deref().unwrap_or("").to_ascii_lowercase();
    if mime.contains("vcf") {
        "VCF"
    } else if mime.contains("bam") {
        "BAM"
    } else if mime.contains("cram") {
        "CRAM"
    } else if mime.contains("fastq") {
        "FASTQ"
    } else {
        "OTHER"
    }
}

fn md5_of(obj: &DrsObject) -> Option<&str> {
    obj.checksums
        .iter()
        .find(|c| c.r#type.eq_ignore_ascii_case("md5"))
        .map(|c| c.checksum.as_str())
}

pub fn bundle_from_objects(profile: &str, objects: &[DrsObject]) -> String {
    let study_type = if profile.eq_ignore_ascii_case("ega") {
        "WHOLE_GENOME_SEQUENCING"
    } else {
        "POPULATION_GENOMICS"
    };
    let mut out = String::new();
    out.push_str("# Generated by `ferrum meta export` from live Ferrum DRS objects.\n");
    out.push_str("# Not a GHGA/EGA acceptance. Starter fixtures: --starter\n");
    out.push_str("ferrum_meta_version: \"0.1.0\"\n\n");
    out.push_str("studies:\n");
    out.push_str("  - alias: ferrum_export_study\n");
    out.push_str("    title: Ferrum live DRS export\n");
    out.push_str(&format!("    type: {study_type}\n\n"));
    out.push_str("files:\n");
    if objects.is_empty() {
        out.push_str("  []\n");
    } else {
        for obj in objects {
            let alias = obj.name.as_deref().unwrap_or(&obj.id);
            out.push_str(&format!("  - alias: {}\n", yaml_escape(alias)));
            out.push_str(&format!("    drs_id: {}\n", yaml_escape(&obj.id)));
            if let Some(uri) = obj.aliases.as_ref().and_then(|a| a.first()) {
                out.push_str(&format!("    drs_uri: {}\n", yaml_escape(uri)));
            } else {
                out.push_str(&format!("    drs_uri: {}\n", yaml_escape(&obj.self_uri)));
            }
            out.push_str(&format!("    format: {}\n", file_format(obj)));
            if let Some(md5) = md5_of(obj) {
                out.push_str(&format!("    checksum_md5: {}\n", yaml_escape(md5)));
            }
            let enc = if obj.is_encrypted == Some(true) {
                "CRYPT4GH"
            } else {
                "NONE"
            };
            out.push_str(&format!("    encryption: {enc}\n"));
        }
    }
    out.push('\n');
    out.push_str("datasets:\n");
    out.push_str("  - alias: ferrum_export_dataset\n");
    out.push_str("    title: Ferrum live DRS dataset\n");
    out.push_str("    file_aliases:\n");
    if objects.is_empty() {
        out.push_str("      []\n");
    } else {
        for obj in objects {
            let alias = obj.name.as_deref().unwrap_or(&obj.id);
            out.push_str(&format!("      - {}\n", yaml_escape(alias)));
        }
    }
    out
}

pub async fn run_meta_export(opts: ExportOpts) -> Result<(), String> {
    let profile = opts.profile.to_ascii_lowercase();
    starter_yaml(&profile)?;
    let body = if opts.starter {
        starter_yaml(&profile)?.to_string()
    } else {
        let base = opts.base_url.trim_end_matches('/');
        let url = format!("{base}/ga4gh/drs/v1/objects?limit=100");
        let mut req = reqwest::Client::new().get(&url);
        if let Some(token) = opts.bearer.as_deref().filter(|t| !t.is_empty()) {
            req = req.bearer_auth(token);
        }
        let res = req
            .send()
            .await
            .map_err(|e| format!("DRS list {url}: {e}"))?;
        if !res.status().is_success() {
            return Err(format!(
                "DRS list {url} HTTP {} (auth-on stacks need --bearer / TEST_BEARER). Starter YAML: --starter",
                res.status()
            ));
        }
        let objects: Vec<DrsObject> = res
            .json()
            .await
            .map_err(|e| format!("DRS list JSON: {e}"))?;
        bundle_from_objects(&profile, &objects)
    };
    if let Some(parent) = opts.output.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
    }
    std::fs::write(&opts.output, body).map_err(|e| e.to_string())?;
    if opts.starter {
        eprintln!(
            "wrote {} — starter fixture, not live DRS. Validate: ferrum-meta/scripts/validate-fixture.sh {}",
            opts.output.display(),
            opts.output.display()
        );
    } else {
        eprintln!(
            "wrote {} — live DRS export. Empty files[] means the gateway had no objects.",
            opts.output.display()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use ferrum_core::Checksum;

    fn obj(id: &str, name: &str, md5: &str) -> DrsObject {
        DrsObject {
            id: id.into(),
            self_uri: format!("drs://example/{id}"),
            size: 1,
            created_time: "2026-01-01T00:00:00Z".into(),
            checksums: vec![Checksum {
                checksum: md5.into(),
                r#type: "md5".into(),
            }],
            name: Some(name.into()),
            updated_time: None,
            version: None,
            mime_type: Some("application/vnd.ga4gh.bam".into()),
            access_methods: None,
            contents: None,
            description: None,
            aliases: None,
            ont_metrics: None,
            gisaid_metadata: None,
            metadata_ref: None,
            storage_backend: None,
            is_encrypted: Some(true),
            workspace_id: None,
            checksum_status: None,
        }
    }

    #[test]
    fn live_export_includes_drs_ids() {
        let yaml = bundle_from_objects("ghga", &[obj("obj-1", "reads.bam", "abc")]);
        assert!(yaml.contains("drs_id: obj-1"));
        assert!(yaml.contains("checksum_md5: abc"));
        assert!(yaml.contains("encryption: CRYPT4GH"));
        assert!(!yaml.contains("ghga_file001"));
    }

    #[test]
    fn empty_node_is_empty_files_not_fixture() {
        let yaml = bundle_from_objects("ega", &[]);
        assert!(yaml.contains("files:\n  []"));
        assert!(!yaml.contains("ega_file001"));
    }
}
