[package]
name = "ferrum-htsget"
version = "0.3.0"
edition = "2021"
license = "BUSL-1.1"
description = "htsget service for Ferrum"
repository = "https://github.com/SynapticFour/Ferrum"

[dependencies]
ferrum-core = { path = "../ferrum-core" }
ferrum-drs = { path = "../ferrum-drs" }
axum = { version = "0.7", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
utoipa = { version = "4" }
utoipa-swagger-ui = { version = "7", features = ["axum"] }
percent-encoding = "2"
