apiVersion: v2
name: ferrum
description: On-premises GA4GH data/compute gateway (DRS, WES, TES, TRS, Beacon, htsget)
type: application
version: 0.3.2
appVersion: "0.3.2"
keywords:
  - ga4gh
  - bioinformatics
  - drs
  - wes
  - tes
  - beacon
sources:
  - https://github.com/SynapticFour/Ferrum
maintainers:
  - name: Synaptic Four
    email: contact@synapticfour.com
