//! Template generation for `ferrum meta init`.

use crate::profiles::MetaProfile;
use crate::FERRUM_META_VERSION;
use serde_json::{json, Value};

#[derive(Debug, Clone, Default)]
pub struct InitParams {
    pub study_title: Option<String>,
    pub study_alias: Option<String>,
    pub sample_alias: Option<String>,
    pub individual_alias: Option<String>,
    pub collection_site: Option<String>,
    pub collection_date: Option<String>,
    pub country: Option<String>,
    pub consent_type: Option<String>,
    pub pathogen_organism: Option<String>,
    pub data_use_conditions: Vec<String>,
}

pub fn build_init_template(profile: MetaProfile, params: &InitParams) -> Value {
    let study_alias = params
        .study_alias
        .clone()
        .unwrap_or_else(|| format!("{}_study001", profile.as_str()));
    let sample_alias = params
        .sample_alias
        .clone()
        .unwrap_or_else(|| "sample001".into());
    let individual_alias = params
        .individual_alias
        .clone()
        .unwrap_or_else(|| "ind001".into());
    let study_title = params
        .study_title
        .clone()
        .unwrap_or_else(|| format!("{} field collection", profile.as_str()));
    let collection_date = params
        .collection_date
        .clone()
        .unwrap_or_else(chrono_lite_today);
    let duo = if params.data_use_conditions.is_empty() {
        match profile {
            MetaProfile::Pathogen => vec!["DUO:0000007".into()],
            MetaProfile::H3Africa => vec!["DUO:0000006".into(), "DUO:0000007".into()],
            MetaProfile::Core => vec!["DUO:0000007".into()],
        }
    } else {
        params.data_use_conditions.clone()
    };

    let (study_type, sample_extra, experiment_extra) = match profile {
        MetaProfile::Core => ("POPULATION_GENOMICS", json!({}), json!({})),
        MetaProfile::Pathogen => (
            "PATHOGEN_SURVEILLANCE",
            json!({
                "collection_date": collection_date,
                "collection_site": params.collection_site.clone().unwrap_or_else(|| "field_site".into()),
            }),
            json!({
                "pathogen_organism": params.pathogen_organism.clone().unwrap_or_else(|| "unknown".into()),
            }),
        ),
        MetaProfile::H3Africa => (
            "H3AFRICA",
            json!({
                "collection_date": collection_date,
                "country": params.country.clone().unwrap_or_else(|| "Kenya".into()),
            }),
            json!({}),
        ),
    };

    let consent = params
        .consent_type
        .clone()
        .unwrap_or_else(|| match profile {
            MetaProfile::H3Africa => "H3AFRICA_BROAD".into(),
            _ => "RESEARCH".into(),
        });

    let mut sample = json!({
        "alias": sample_alias,
        "individual_alias": individual_alias,
        "tissue_type": "whole blood",
    });
    if let Some(obj) = sample_extra.as_object() {
        for (k, v) in obj {
            sample[k] = v.clone();
        }
    }

    let mut experiment = json!({
        "alias": "exp001",
        "sample_alias": sample_alias,
        "sequencing_platform": "OXFORD_NANOPORE",
        "library_strategy": if profile == MetaProfile::Pathogen { "AMPLICON" } else { "WGS" },
    });
    if let Some(obj) = experiment_extra.as_object() {
        for (k, v) in obj {
            experiment[k] = v.clone();
        }
    }

    json!({
        "ferrum_meta_version": FERRUM_META_VERSION,
        "studies": [{
            "alias": study_alias,
            "title": study_title,
            "description": format!("Generated by ferrum meta init ({})", profile.as_str()),
            "type": study_type,
            "data_use_conditions": duo,
        }],
        "individuals": [{
            "alias": individual_alias,
            "sex": "UNKNOWN",
            "consent_type": consent,
        }],
        "samples": [sample],
        "experiments": [experiment],
        "files": [{
            "alias": format!("{sample_alias}.fastq.gz"),
            "format": "FASTQ",
            "encryption": "CRYPT4GH",
        }],
        "datasets": [{
            "alias": format!("dataset_{sample_alias}"),
            "title": format!("Dataset for {sample_alias}"),
            "description": "Field collection metadata",
            "file_aliases": [format!("{sample_alias}.fastq.gz")],
        }],
    })
}

fn chrono_lite_today() -> String {
    // Avoid chrono dependency in this crate — callers on CLI can pass explicit dates.
    "2026-06-18".into()
}
