use ferrum_crypt4gh::{stream_decrypt, C4ghKeys};
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};
use tokio::fs;

fn temp_path(name: &str) -> PathBuf {
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("time")
        .as_nanos();
    std::env::temp_dir().join(format!("ferrum-c4gh-{name}-{ts}"))
}

/// Ferrum must be able to decrypt Crypt4GH ciphertexts generated by the
/// `crypt4gh` Python reference implementation.
#[tokio::test]
async fn test_can_decrypt_python_encrypted_file() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let keys_dir = manifest.join("tests/keys");
    let fixtures_dir = manifest.join("tests/fixtures");

    let alice_sec = keys_dir.join("python_ref_alice.sec");
    let alice_pub = keys_dir.join("python_ref_alice.pub");
    let encrypted = fixtures_dir.join("python_encrypted.c4gh");
    let expected_plaintext = fixtures_dir.join("plaintext.txt");

    let expected = fs::read(&expected_plaintext)
        .await
        .expect("read expected plaintext");

    // Load Python-generated private key (created with `--nocrypt`, but the callback is harmless).
    let privkey = crypt4gh::keys::get_private_key(&alice_sec, || Ok(String::new()))
        .expect("read python_ref_alice.sec");
    // `crypt4gh` may return only the 32-byte Curve25519 private key.
    // Decryption does not require `recipient_pubkey`, so we can keep it empty.
    let recipient_pubkey = crypt4gh::keys::get_public_key(&alice_pub)
        .ok()
        .unwrap_or_default();

    let dec_key = C4ghKeys {
        method: 0,
        privkey,
        recipient_pubkey,
    };

    let root = temp_path("python-interop");
    fs::create_dir_all(&root).await.expect("mkdir");
    let out = root.join("out.bin");

    let r = fs::File::open(&encrypted)
        .await
        .expect("open encrypted fixture");
    let w = fs::File::create(&out).await.expect("create output");
    stream_decrypt(&[dec_key], r, w, None)
        .await
        .expect("stream_decrypt python fixture");

    let got = fs::read(&out).await.expect("read output");
    let _ = fs::remove_dir_all(&root).await;

    assert_eq!(
        got, expected,
        "decrypted bytes must match the python reference plaintext"
    );
}
